CC = g++ -std=c++20
CXX = g++ -std=c++20

INCLUDES = -I../include

CXXFLAGS = -g -Wall -O2 $(INCLUDES)

LDFLAGS = 
LDLIBS = 

test_model:

.PHONY:
clean:
	rm -rf *.o a.out *.dSYM test_model

.PHONY:
all: clean test_model 
